before_commands:
    - composer install --dev
tools:
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        filter:
            paths: ["Gruntfile.js", "js/bbcode.js"]
            excluded_paths: ["vendor", "node_modules", "components"]
    php_changetracking:
        enabled: true
    php_code_sniffer:
        config:
            ruleset: Ruleset.xml
            standard: PSR2
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            excluded_paths: ["vendor", "node_modules", "components"]
            paths: ["*.php"]

