before_commands:
    - composer install --dev
tools:
    php_sim:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_changetracking:
        enabled: true
    php_mess_detector:
        enabled: true
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        filter:
            paths: ["Gruntfile.js", "js/bbcode.js"]
            excluded_paths: ["vendor", "node_modules", "components"]
    php_cpd:
        command: phpcpd
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs: ["vendor", "node_modules", "components"]
        enabled: true
    php_code_sniffer:
        config:
            ruleset: Ruleset.xml
            standard: PSR2
        extensions:
            - php
        command: phpcs
        enabled: true
        filter:
            excluded_paths: ["vendor", "node_modules", "components"]
            paths: ["*.php"]
