filter:
    excluded_paths:
        - tests/
        - vendor/
        - components/
        - node_modules/
before_commands:
    - composer install
tools:
    sensiolabs_security_checker:
        enabled: true
    php_sim:
        enabled: true
        filter:
            excluded_paths:
                - tests/
                - vendor/
                - components/
                - node_modules/
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
        filter:
            excluded_paths:
                - tests/
                - vendor/
                - components/
                - node_modules/
    php_changetracking:
        enabled: true
    php_mess_detector:
        enabled: true
    js_hint:
        enabled: true
        use_native_config: true
        extensions:
            - js
        filter:
            paths: ["Gruntfile.js", "js/bbcode.js"]
            excluded_paths:
                - tests/
                - vendor/
                - components/
                - node_modules/
    php_cpd:
        min_lines: 5
        min_tokens: 70
        names:
            - '*.php'
        excluded_dirs:
            - tests/
            - vendor/
            - components/
            - node_modules/
        enabled: false
    php_code_sniffer:
        config:
            ruleset: development/Ruleset.xml
            standard: PSR2
        extensions:
            - php
        enabled: true
        filter:
            paths: ["*.php"]
